# Generated by Django 4.0.5 on 2022-06-22 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_alter_lection_author_homeworksolution_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworksolution",
            name="rating",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
