# Generated by Django 4.0.5 on 2022-06-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_alter_homeworksolution_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="lection",
            name="pdf",
            field=models.FileField(null=True, upload_to="lections"),
        ),
    ]
