# Generated by Django 4.0.5 on 2022-06-23 18:18

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_lection_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lection",
            name="pdf",
            field=models.FileField(
                null=True, upload_to=exercises.models.Lection._upload
            ),
        ),
    ]
